services:
  - type: web
    name: liga-neo-egoist
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: liga-db
          property: connectionString

databases:
  - name: liga-db
    plan: free
    databaseName: liga_neo_egoist
