services:
  - type: web
    name: liga-neo-egoist
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APP_ENV
        value: production
      - key: postgresql://neondb_owner:npg_uGgSwtv8Wb1i@ep-little-frost-b5uwqulj-pooler.c-7.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
        sync: false

databases:
  - name: liga-db
    plan: free
    databaseName: liga_neo_egoist
